### PR TITLE
Add %f() syntax for frozen strings

### PR DESCRIPTION
**Pull request by haileys**
cc @github/perf @github/systems

### CODE REVIEW

**Comment by tmm1** [comment]
I have mixed feeling about this. Curious to see some benchmarks before we start using a new syntax that's divergent from upstream.

**Comment by haileys** [comment]
@tmm1 If the new syntax bothers you, how about we add a `__frozen__` method that is treated as an instrinsic by the compiler in our fork of Ruby?

**Comment by tmm1** [comment]
I like the syntax, I'm just weary of adding language features and ending up with a diverging ruby fork and internal codebases that only work with the new features.

I think this is going to be worth it though. Let's see how much it helps in the template rendering case.

**Comment by haileys** [comment]
@tmm1 Yeah fair point. We should definitely avoid using this syntax in hand written code I think. We'll see most of the benefit from using it in generated code.

At any rate, I've proposed this syntax to ruby-core so it _may_ be included in Ruby 2.1.

**Comment by vmg** [comment]
This is an _objectively_ nice feature. I think we (and by we I mean you) should pressure upstream into adding this for 2.1, and get very upset if it doesn't make it in.

**Comment by haileys** [comment]
@vmg feel free to weigh in with your support: https://bugs.ruby-lang.org/issues/8579

**Pull request merged**
